# Generated by Django 6.0.4 on 2026-09-13 17:11

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
