# Generated by Django 6.0.4 on 2026-09-14 04:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_chunk_embedding_hnsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('text', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('text', 'Pasted text'), ('pdf', 'PDF'), ('docx', 'Word document'), ('plain', 'Text/Markdown file')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin'),
        ),
    ]
