"""
Django settings for AI_Assistant project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _csv_env(name: str) -> list[str]:
    return [v.strip() for v in os.getenv(name, "").split(",") if v.strip()]


# =============================================================================
# ENVIRONMENT SWITCH  —  choose "dev" (local) or "prod" (Azure)
# =============================================================================
# Local:      leave as-is (defaults to "dev").
# Production: Azure App Service sets  DJANGO_ENV=prod  (see deploy steps).
# You do NOT need to comment anything out — flip this one variable.
# (If you prefer commenting, comment out the block you are NOT using below.)
DJANGO_ENV = os.getenv("DJANGO_ENV", "dev").lower()
IS_PROD = DJANGO_ENV == "prod"


if not IS_PROD:
    # -------------------------------------------------------------------------
    # DEVELOPMENT  (local machine)
    # -------------------------------------------------------------------------
    DEBUG = True
    SECRET_KEY = "django-insecure-ka6^6cwex5=3gslw#f6kfbn9+kfw5$bj*_l71is-x0ggwoyjdi"
    ALLOWED_HOSTS = ["*"]
    CSRF_TRUSTED_ORIGINS = []

    # Local Postgres from docker-compose.yml
    DATABASES = {
        "default": dj_database_url.parse(
            "postgres://aiassistant:aiassistant@127.0.0.1:5433/aiassistant",
            conn_max_age=600,
        )
    }

    # Frontend runs on Vite dev server — allow everything locally
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []

    # Throttle counters live in memory locally (per process is fine for one runserver)
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

else:
    # -------------------------------------------------------------------------
    # PRODUCTION  (Azure — all secrets come from App Service settings)
    # -------------------------------------------------------------------------
    DEBUG = False
    SECRET_KEY = os.environ["SECRET_KEY"]                       # required in prod
    ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS")                   # e.g. myapp.azurewebsites.net
    CSRF_TRUSTED_ORIGINS = _csv_env("CSRF_TRUSTED_ORIGINS")     # https://myapp.azurewebsites.net

    # Azure Database for PostgreSQL via DATABASE_URL (SSL required unless
    # DATABASE_SSL_REQUIRE=false, which is only for trying prod mode locally)
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=os.getenv("DATABASE_SSL_REQUIRE", "true").lower() != "false",
        )
    }

    # Only allow the deployed frontend origin(s)
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _csv_env("CORS_ALLOWED_ORIGINS")     # https://myapp.azurestaticapps.net

    # Throttle counters are shared by all gunicorn workers (table made by `createcachetable`)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_cache",
        }
    }

    # HTTPS hardening (App Service terminates TLS; enable "HTTPS Only" on the app)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "3600"))
    SECURE_REFERRER_POLICY = "same-origin"


# Adding documents: open locally, locked in prod unless the X-Ingest-Key header matches.
INGEST_API_KEY = os.getenv("INGEST_API_KEY", "")
INGEST_OPEN = not IS_PROD and not INGEST_API_KEY


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',
    'rag_app',
    'pgvector',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AI_Assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AI_Assistant.wsgi.application'


# Database is configured in the ENVIRONMENT SWITCH block near the top.


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}

# CORS is configured in the ENVIRONMENT SWITCH block near the top.
CORS_ALLOW_HEADERS = (*default_headers, "x-ingest-key")

# Trust the proxy's forwarded protocol (App Service terminates TLS)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Django REST Framework
# The API is public and stateless: no session auth (so no CSRF on API calls),
# JSON only in prod, and per-IP rate limits to protect LLM spend.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "UNAUTHENTICATED_USER": None,
    "DEFAULT_RENDERER_CLASSES": (
        ["rest_framework.renderers.JSONRenderer"]
        if IS_PROD
        else [
            "rest_framework.renderers.JSONRenderer",
            "rest_framework.renderers.BrowsableAPIRenderer",
        ]
    ),
    "DEFAULT_THROTTLE_RATES": {
        "ask": os.getenv("THROTTLE_ASK_RATE", "30/hour"),
        "ingest": os.getenv("THROTTLE_INGEST_RATE", "10/hour"),
        # Each agent request makes several model calls, so it gets a lower limit.
        "agent": os.getenv("THROTTLE_AGENT_RATE", "15/hour"),
    },
}


# Logging: everything to stdout so App Service "Log stream" shows it
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "plain": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "plain"},
    },
    "root": {"handlers": ["console"], "level": os.getenv("LOG_LEVEL", "INFO")},
    "loggers": {
        "django.security.DisallowedHost": {"handlers": ["console"], "level": "ERROR", "propagate": False},
    },
}
